In [144]:
import pandas as pd
import requests as r
from bs4 import BeautifulSoup as bs
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns


# Task: Columns -> Energy & Petrol Consumption, Storage

In [ ]:
base_url = "https://www.fueleconomy.gov/feg/"
makers = ["Chevrolet", "Ford", "Nissan"]

def get_data(base, maker):
    mpge = []
    mpg = []
    battery = []
    gas_tank = []
    links = []
    
    manufacturers = []
    years = []
    models = []
    miles_IRA = [] 

    emissions = []
    types = []
    min_prices = []
    max_prices = []
    
    for m in maker:
        page = 1
        while True:
            print(f"Scraping page {page} of {m}")
            maker_url = f"{base}PowerSearch.do?action=noform&path=4&year1=2019&year2=2024&make={m}&srchtyp=newMake&pageno={page}&rowLimit=200"
            response = r.get(maker_url)
            soup = bs(response.content)
            cars = soup.find_all("tr", class_ = "ymm-row")
            if not cars:
                break

            for tr in cars:
                a_tags = tr.find_all("a")
                emission_elem = soup.find_all("div", class_="ghg-score")
                for e in emission_elem:
                    emission_value = e.get_text(strip=True).split()[0] if emission_elem else None
                    emissions.append(emission_value)

                price_elem = soup.find_all("td", class_="msrp")
                for e in price_elem:
                    if price_elem:
                        price_text = e.get_text(strip=True)
                        cleaned_price = price_text.replace('$', '').replace(',', '')  # Remove $ and comma
                        price_parts = cleaned_price.split('â€“')
                        price_parts = [part.strip() for part in price_parts if part]
            
                        if len(price_parts) == 1:
                            min_price = float(price_parts[0])
                            max_price = float(price_parts[0])
                        elif len(price_parts) == 2:
                            min_price = float(price_parts[0])
                            max_price = float(price_parts[1])
                        else:
                            min_price = None
                            max_price = None
    
                        min_prices.append(min_price)
                        max_prices.append(max_price)

                config_span = soup.find_all("span", class_="config")
                for e in config_span:
                    car_type_text = e.get_text(strip=True) if config_span else None
                    car_type = "Electricity" if "Electricity" in car_type_text else "Regular Gasoline" if "Regular Gasoline" in car_type_text else "Unknown"
                    types.append(car_type)
            for a in a_tags:
                manufacturers.append(a.text.split()[1])
                years.append(a.text.split()[0])
                models.append(' '.join(a.text.split()[2:]))   

            miles_IRA.extend([mile_IRA.get_text() for mile_IRA in soup.find_all("div", class_="totalRange")])
            
            link = [x.get("href") for x in soup.select("a[href]") if "sbs&id" in x.get("href")]

            for l in link:
                if l == "#":
                    continue
                links.append(l)
                response = r.get(base+l)
                soup = bs(response.content)
                try:
                    type = soup.find("td", class_="fuel nobottomborder padding").getText(strip=True)
                except:
                    print(f"No type: {l}")
                try:
                    if type == "Electricity":
                        battery.append(soup.find_all("td", class_="even sbsCellData")[2].getText().split(" ")[0]) #hrs per 240v
                        gas_tank.append(0)
                        mpge.append(soup.find("td", class_="combinedMPG").getText().split(":")[1])
                        mpg.append(0)
                    elif type in ["Regular Gasoline", "Diesel", "Premium Gasoline"]:
                        battery.append(0)
                        if soup.find_all("td", class_="sbsEconData")[2].getText().split(" ")[0] == "E85:":
                            gas_tank.append(soup.find_all("td", class_="sbsEconData")[5].getText().split(" ")[0])
                        else:
                            gas_tank.append(soup.find_all("td", class_="sbsEconData")[2].getText().split(" ")[0]) #gallons
                        mpge.append(0)
                        mpg.append(soup.find("td", class_="combinedMPG").getText().split(":")[1])
                    else:
                        battery.append(soup.find_all("td", class_="even sbsCellData")[2].getText().split(" ")[0]) #hrs per 240v
                        gas_tank.append(soup.find_all("td", class_="sbsEconData")[3].getText().split(" ")[0]) #gallons
                        mpge.append(soup.find("td", class_="combinedMPG").getText().split(":")[1])
                        mpg.append(soup.find("td", class_="combinedMPG").getText().split(":")[1])
                except:
                    print(f"Process stopped at {l}")
            page += 1
            
    miles_IRA = miles_IRA[:len(manufacturers)] 
    
    print("Creating Dictionary.")
    print("\n")

    manufacturer_dict = {"manufacturers":manufacturers, "year":years, "model":models, "total_range_in_miles":miles_IRA,
                         'emission_value': emissions, 'min_price': min_prices, 'max_price': max_prices, 'car_type': types,
                         "electric_consumption":mpge, "electric_storage":battery, 
                         "analogue_consumption":mpg, "analogue_storage":gas_tank, "links":links}
    print("\n")
    print("Checking Dataframe.")
    for x,y in manufacturer_dict.items:
        print(f"{x}: {len(y)}")
    print("Creating Dataframe.")
    return pd.DataFrame(manufacturer_dict)

manufacturer_df = get_data(base_url, makers)
print("Finished")

In [ ]:
manufacturer_df_copy = manufacturer_df

In [ ]:
manufacturer_df_copy["analogue_storage"] = manufacturer_df_copy["analogue_storage"].astype(str).apply(lambda x: (int(float(x.split("-")[0]))+
                                                                                                                 int(float(x.split("-")[1])))/2
                                                                                                      if "-" in x else x)
manufacturer_df_copy["analogue_storage"] = manufacturer_df_copy["analogue_storage"].apply(lambda x: 0 if not x else x)
manufacturer_df_copy['year'] = manufacturer_df_copy['year'].astype(int)
manufacturer_df_copy['total_range_in_miles'] = manufacturer_df_copy['total_range_in_miles'].str.split().str[0].astype(int)

In [ ]:
manufacturer_df_copy

In [152]:
manufacturer_df_copy.to_csv('sergej_df.csv', index=False)

In [163]:
s_df = pd.read_csv("sergej_df.csv")
m_df = pd.read_csv("mateo_df.csv")
r_df = pd.read_csv("rosi_df.csv")

In [164]:
all_df = pd.concat([m_df,s_df,r_df], axis=1)

In [177]:
all_df.head(3)

,manufacturer,year,model,total_range_in_mls,electric_consumption,electric_storage,analogue_consumption,analogue_storage,emission_value,min_price,max_price,car_type
0,Chevrolet,2023,Bolt EV,259,120,7.5,0,0.0,0,26500.0,29700.0,Electricity
1,Chevrolet,2022,Bolt EV,259,120,7.5,0,0.0,0,31000.0,34200.0,Electricity
2,Chevrolet,2019,Bolt EV,238,119,9.3,0,0.0,0,36620.0,41020.0,Electricity

In [176]:
all_df.isna().sum()
all_df.duplicated().sum()
all_df.fillna(0)
all_df.drop_duplicates()

,manufacturer,year,model,total_range_in_mls,electric_consumption,electric_storage,analogue_consumption,analogue_storage,emission_value,min_price,max_price,car_type
0,Chevrolet,2023,Bolt EV,259,120,7.5,0,0.0,0,26500.0,29700.0,Electricity
1,Chevrolet,2022,Bolt EV,259,120,7.5,0,0.0,0,31000.0,34200.0,Electricity
2,Chevrolet,2019,Bolt EV,238,119,9.3,0,0.0,0,36620.0,41020.0,Electricity
3,Chevrolet,2021,Bolt EV,259,118,10.0,0,0.0,0,36500.0,41700.0,Electricity
4,Chevrolet,2020,Bolt EV,259,118,10.0,0,0.0,0,36620.0,41020.0,Electricity
...,...,...,...,...,...,...,...,...,...,...,...,...
1286,Nissan,2022,Armada 4WD,416,0,0.0,15,26.0,631,NaN,NaN,Premium Gasoline
1287,Nissan,2021,Armada 4WD,416,0,0.0,15,26.0,631,59140.0,72135.0,Premium Gasoline
1288,Nissan,2021,Armada 4WD,416,0,0.0,15,26.0,654,NaN,NaN,Premium Gasoline
1289,Nissan,2020,Armada 4WD,390,0,0.0,15,26.0,741,NaN,NaN,Regular Gasoline
1290,Nissan,2019,Armada 4WD,390,0,0.0,15,26.0,741,107350.0,107350.0,Regular Gasoline

NameError: name 'duplicated' is not defined